/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Models/Solar_System.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
const GLTF_LOADER =
  "https://cdn.jsdelivr.net/gh/AhmedAl-Bahrawy/Are-We-Ready---Nile-Stars-Nasa-Models@main/SolarSystem.glb";

export default function SolarSystem(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(GLTF_LOADER);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // Play all animations
      Object.values(actions).forEach((action) => {
        if (action) {
          action.reset().play();
        }
      });

      // Stop all animations after 40 seconds
      const timer = setTimeout(() => {
        Object.values(actions).forEach((action) => {
          if (action) {
            action.stop();
          }
        });
      }, 25000); // 40,000 ms = 40 sec

      // Cleanup on unmount
      return () => {
        clearTimeout(timer);
        Object.values(actions).forEach((action) => {
          if (action) {
            action.stop();
          }
        });
      };
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="mercury_Empty"
          rotation={[Math.PI / 2, 0, 0]}
          scale={9.695}
        >
          <mesh
            name="mercury_BezierCircle"
            geometry={nodes.mercury_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, -0.071, 0]}
          >
            <mesh
              name="mercury"
              geometry={nodes.mercury.geometry}
              material={materials.mercury}
              position={[0, 0, 1]}
              rotation={[1.739, -0.875, 1.237]}
              scale={0.038}
            />
          </mesh>
        </group>
        <group name="venus_Empty" rotation={[Math.PI / 2, 0, 0]} scale={12.235}>
          <mesh
            name="venus_BezierCircle"
            geometry={nodes.venus_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="venus"
              geometry={nodes.venus.geometry}
              material={materials.venus}
              position={[0, 0, 1]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.102}
            />
          </mesh>
        </group>
        <group name="erath_Empty" rotation={[1.161, 0, 0]} scale={16.115}>
          <mesh
            name="erath_BezierCircle"
            geometry={nodes.erath_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, -0.017, 0]}
          >
            <group
              name="moon_Empty"
              position={[0, 0, 1]}
              rotation={[1.891, 0, 0]}
              scale={-0.117}
            >
              <mesh
                name="moon_BezierCircle"
                geometry={nodes.moon_BezierCircle.geometry}
                material={materials.Material}
                rotation={[-Math.PI / 2, -0.224, 0]}
              >
                <mesh
                  name="moon"
                  geometry={nodes.moon.geometry}
                  material={materials.moon}
                  position={[0, 0, 1]}
                  rotation={[-0.023, 0, Math.PI / 2]}
                  scale={0.096}
                />
              </mesh>
            </group>
            <mesh
              name="erath"
              geometry={nodes.erath.geometry}
              material={materials.earth}
              position={[0, 0, 1]}
              rotation={[0.819, 0, 0]}
              scale={0.062}
            />
          </mesh>
        </group>
        <group name="mars_Empty" rotation={[Math.PI / 2, 0, 0]} scale={20.451}>
          <mesh
            name="mars_BezierCircle"
            geometry={nodes.mars_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, -0.009, 0]}
          >
            <mesh
              name="mars"
              geometry={nodes.mars.geometry}
              material={materials.mars}
              position={[0, 0, 1]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.025}
            />
          </mesh>
        </group>
        <group name="jupiter_Empty" rotation={[1.446, 0, 0]} scale={28.775}>
          <mesh
            name="jupiter_BezierCircle"
            geometry={nodes.jupiter_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, -0.001, 0]}
          >
            <mesh
              name="jupiter"
              geometry={nodes.jupiter.geometry}
              material={materials.jupiter}
              position={[0, 0, 1]}
              scale={0.095}
            />
          </mesh>
        </group>
        <group name="saturn_Empty" rotation={[1.71, 0, 0]} scale={36.61}>
          <mesh
            name="saturn_BezierCircle"
            geometry={nodes.saturn_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, -0.001, 0]}
          >
            <mesh
              name="saturn"
              geometry={nodes.saturn.geometry}
              material={materials.saturn}
              position={[0, 0, 1]}
              scale={0.059}
            >
              <mesh
                name="saturn_ring"
                geometry={nodes.saturn_ring.geometry}
                material={materials.saturn_ring}
                position={[0.01, -0.067, 0]}
                rotation={[0, 0, 0.351]}
                scale={1.739}
              />
            </mesh>
          </mesh>
        </group>
        <group name="uranus_Empty" rotation={[1.76, 0, 0]} scale={44.26}>
          <mesh
            name="uranus_BezierCircle"
            geometry={nodes.uranus_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="uranus"
              geometry={nodes.uranus.geometry}
              material={materials.uranus}
              position={[0, 0, 1]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.02}
            />
          </mesh>
        </group>
        <group
          name="neptune_Empty"
          rotation={[Math.PI / 2, 0, 0]}
          scale={49.927}
        >
          <mesh
            name="neptune_BezierCircle"
            geometry={nodes.neptune_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="neptune"
              geometry={nodes.neptune.geometry}
              material={materials.neptune}
              position={[0, 0, 1]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.024}
            />
          </mesh>
        </group>
        <group name="pluto_Empty" rotation={[2.077, 0, 0]} scale={54.22}>
          <mesh
            name="pluto_BezierCircle"
            geometry={nodes.pluto_BezierCircle.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="pluto"
              geometry={nodes.pluto.geometry}
              material={materials.pluto}
              position={[0, 0, 1]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.004}
            />
          </mesh>
        </group>
        <mesh
          name="sun"
          geometry={nodes.sun.geometry}
          material={materials.sun}
          rotation={[0, -0.262, 0]}
          scale={5.997}
        />
      </group>
    </group>
  );
}

useGLTF.preload(GLTF_LOADER);
